/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fff8f6',
        'surface-dim': '#ecd5ce',
        'surface-bright': '#fff8f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff1ec',
        'surface-container': '#ffe9e2',
        'surface-container-high': '#fbe3dc',
        'surface-container-highest': '#f5ded6',
        'on-surface': '#251914',
        'on-surface-variant': '#584239',
        'inverse-surface': '#3b2d28',
        'inverse-on-surface': '#ffede7',
        outline: '#8c7168',
        'outline-variant': '#dfc0b5',
        'surface-tint': '#a63b00',
        primary: '#a63b00',
        'on-primary': '#ffffff',
        'primary-container': '#c8521a',
        'on-primary-container': '#100200',
        'inverse-primary': '#ffb599',
        secondary: '#58614e',
        'on-secondary': '#ffffff',
        'secondary-container': '#d9e3ca',
        'on-secondary-container': '#5c6652',
        tertiary: '#a73828',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c8503e',
        'on-tertiary-container': '#140000',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fff8f6',
        'on-background': '#251914',
        'surface-variant': '#f5ded6',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        serif: ['"Noto Serif"', 'Georgia', 'serif'],
      },
    },
  },
  plugins: [],
};
