/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: '#D97706', // Saffron
          secondary: '#B45309',
          bg: '#0A0A0A', // Stone/Obsidian
          surface: '#0D0D0D',
          card: '#121212',
          outline: 'rgba(217, 119, 6, 0.2)',
        },
        saffron: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
          950: '#451a03',
        },
        surface: '#fff8f6',
        'surface-dim': '#ecd5ce',
        'surface-bright': '#fff8f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff1ec',
        'surface-container': '#ffe9e2',
        'surface-container-high': '#fbe3dc',
        'surface-container-highest': '#f5ded6',
        'on-surface': '#251914',
        'on-surface-variant': '#584239',
        'inverse-surface': '#3b2d28',
        'inverse-on-surface': '#ffede7',
        outline: '#8c7168',
        'outline-variant': '#dfc0b5',
        'surface-tint': '#a63b00',
        primary: '#f59e0b', // saffron-500
        'on-primary': '#ffffff',
        'primary-container': '#c8521a',
        'on-primary-container': '#100200',
        'primary-fixed': '#ffdbce',
        'primary-fixed-dim': '#ffb599',
        'on-primary-fixed': '#370e00',
        'on-primary-fixed-variant': '#7f2b00',
        'inverse-primary': '#ffb599',
        secondary: '#58614e',
        'on-secondary': '#ffffff',
        'secondary-container': '#d9e3ca',
        'on-secondary-container': '#5c6652',
        'secondary-fixed': '#dce6cd',
        'secondary-fixed-dim': '#c0cab2',
        'on-secondary-fixed': '#161e0e',
        'on-secondary-fixed-variant': '#404a37',
        tertiary: '#a73828',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c8503e',
        'on-tertiary-container': '#140000',
        'tertiary-fixed': '#ffdad4',
        'tertiary-fixed-dim': '#ffb4a7',
        'on-tertiary-fixed': '#400100',
        'on-tertiary-fixed-variant': '#872114',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fff8f6',
        'on-background': '#251914',
        'surface-variant': '#f5ded6',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        serif: ['"Noto Serif"', 'Georgia', 'serif'],
        'display-lg': ['"Noto Serif"'],
        'headline-md': ['"Noto Serif"'],
        'headline-sm': ['"Noto Serif"'],
        'body-lg': ['"Plus Jakarta Sans"'],
        'body-md': ['"Plus Jakarta Sans"'],
        'price-lg': ['"Plus Jakarta Sans"'],
        'label-caps': ['"Plus Jakarta Sans"'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'price-lg': ['20px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        base: '8px',
        gutter: '24px',
        'container-max': '1200px',
      },
      animation: {
        'ken-burns': 'ken-burns 20s ease-in-out infinite alternate',
      },
      keyframes: {
        'ken-burns': {
          '0%': { transform: 'scale(1.1) translate(0, 0)' },
          '100%': { transform: 'scale(1.2) translate(-2%, -2%)' },
        }
      }
    },
  },
  plugins: [],
};
